baseurl = "/"
languageCode = "en-us"
theme = "anatole"
paginate = 15
enableEmoji = true
summarylength = 10

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[params]
  profilePicture = "images/me-avatar.png"
  title = "FYI I'm Ernesto"
  author = "Ernesto Arbitrio"
  description = "Call me pamaron"
  gtagId = "G-L18ZJ5LY2H"
  enableRobotsTXT = true
  favicon = "favicons/"
  contentratio = 0.75
  readMore = true
  showLanguageSelector = false
  showLastUpdated = false
  oldContentWarning = true
  oldContentDuration = 365
  reversepagetitle = true
  mainSections = ["posts"]
  customCss = ["css/custom.css"]
  LanguageDirection = "rtl"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'dracula'
    tabWidth = 4
  

[[params.socialIcons]]
icon = "fab fa-github"
title = "github"
url = "https://github.com/ernestoarbitrio"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/__pamaron__"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/ernestoarbitrio/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:ernesto@arbitrio.fyi"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
